services:
  flight_service:
    build:
      context: flight_service
    environment:
      FLIGHT_SERVICE_DB_PROTOCOL: ${FLIGHT_SERVICE_DB_PROTOCOL}
      FLIGHT_SERVICE_DB_USER: ${FLIGHT_SERVICE_DB_USER}
      FLIGHT_SERVICE_DB_PASSWORD: ${FLIGHT_SERVICE_DB_PASSWORD}
      FLIGHT_SERVICE_DB_HOST: postgres
      FLIGHT_SERVICE_DB_PORT: ${FLIGHT_SERVICE_DB_PORT}
      FLIGHT_SERVICE_DB_NAME: ${FLIGHT_SERVICE_DB_NAME}
    ports:
      - 8060:8060
    depends_on:
      postgres:
        condition: service_started

  ticket_service:
    build:
      context: ticket_service
    environment:
      TICKET_SERVICE_DB_PROTOCOL: ${TICKET_SERVICE_DB_PROTOCOL}
      TICKET_SERVICE_DB_USER: ${TICKET_SERVICE_DB_USER}
      TICKET_SERVICE_DB_PASSWORD: ${TICKET_SERVICE_DB_PASSWORD}
      TICKET_SERVICE_DB_HOST: postgres
      TICKET_SERVICE_DB_PORT: ${TICKET_SERVICE_DB_PORT}
      TICKET_SERVICE_DB_NAME: ${TICKET_SERVICE_DB_NAME}
    ports:
      - 8070:8070
    depends_on:
      postgres:
        condition: service_started

  postgres:
    image: postgres:18
    restart: on-failure
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: postgres
    volumes:
      - db-data:/var/lib/postgresql
      - ./postgres/:/docker-entrypoint-initdb.d/
    expose:
      - 5432
volumes:
  db-data:
